name: pick_tube_image_tactile_emb_ldp_30fps
dataset_path: data/pick_tube_01_06_pca30_rdp_zarr
image_shape: [3, 224, 224]

shape_meta: &shape_meta
  obs:
    camera1:
      shape: ${task.image_shape}
      type: rgb
    camera2:
      shape: ${task.image_shape}
      type: rgb
    observation_state:
      shape: [20]
      type: low_dim
    tactile_embedding:
      shape: [30]
      type: low_dim
  extended_obs:
    tactile_embedding:
      shape: [30]
      type: low_dim
  action:
    shape: [20]

dataset:
  _target_: reactive_diffusion_policy.dataset.real_image_tactile_latent_diffusion_dataset.RealImageTactileLatentDiffusionDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${dataset_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  obs_temporal_downsample_ratio: ${dataset_obs_temporal_downsample_ratio}
  n_latency_steps: ${n_latency_steps}
  seed: 42
  val_ratio: 0.0
  max_train_episodes: null
  use_episode_repeats: false
  delta_action: false
  relative_action: false
  transform_params: null
  load_to_memory: false
  bimanual_contiguous_action: true
  use_latent_action_before_vq: false
  at:
    _target_: reactive_diffusion_policy.model.vae.model.VAE
    shape_meta: ${shape_meta}
    horizon: ${at.policy.horizon}
    n_latent_dims: ${at.policy.n_latent_dims}
    mlp_layer_num: ${at.policy.mlp_layer_num}
    use_conv_encoder: ${at.policy.use_conv_encoder}
    conv_latent_dims: ${at.policy.conv_latent_dims}
    conv_layer_num: ${at.policy.conv_layer_num}
    use_rnn_decoder: ${at.policy.use_rnn_decoder}
    rnn_latent_dims: ${at.policy.rnn_latent_dims}
    rnn_layer_num: ${at.policy.rnn_layer_num}
    use_vq: ${at.policy.use_vq}
    n_embed: ${at.policy.n_embed}
    vqvae_groups: ${at.policy.vqvae_groups}
    eval: true
    load_dir: ${at_load_dir}
    act_scale: ${at.policy.act_scale}
