task: pick up two tubes

model:
  ldp_checkpoint: /home/typhon/RDP_vitamin/data/weights/wjstx_rdp/tactile/rdp/60/ldp/latest.ckpt
  at_checkpoint: /home/typhon/RDP_vitamin/data/weights/wjstx_rdp/tactile/rdp/60/at/latest.ckpt
  tactile_encoder_dir: data/encoder_ckpt_0809
  tactile_pca_path: /home/typhon/RDP_vitamin/data/weights/wjstx_rdp/tactile/rdp/tactile_pca_armwise_01_02_03_04_05_06_2x30.npz
  device: cuda:0
  num_inference_steps: 8

connection:
  address: 127.0.0.1
  port: 26421
  add_port: true
  retry_interval_s: 1.0
  action_ack_timeout_s: 3.0
  token_env: VB_ROBOT_TOKEN
  require_token: true

control:
  control_frequency: 30.0
  controller_frequency: 80.0
  slow_update_interval: 16

runtime:
  auto_start: false
  warmup_runs: 2
  status_interval_s: 2.0
  max_iterations: 0
