defaults:
  - train_at_workspace
  - override /task: pick_tube_image_tactile_emb_at_30fps
  - override /at: at_pick_tube
  - _self_

n_action_steps: 10
dataset_obs_steps: 1
dataset_obs_temporal_downsample_ratio: 1

dataloader:
  batch_size: 64
  num_workers: 4

val_dataloader:
  batch_size: 64
  num_workers: 4

training:
  mixed_precision: bf16
