defaults:
  - train_latent_diffusion_unet_real_image_workspace
  - override /task: pick_tube_image_tactile_emb_ldp_30fps
  - override /at: at_pick_tube
  - _self_

policy:
  obs_encoder:
    resize_shape: [224, 224]

# Keep the official method/model settings, but shorten training for this much
# larger dataset.
training:
  num_epochs: 10
  checkpoint_every: 2
